# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qb9-kapxJSdsWuty7OAhVAVaIC9Vkdao
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv('/content/loan_data.csv')

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

X = df.drop('loan_status', axis=1)
y = df['loan_status']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

import joblib
joblib.dump(model, "loan_model.pkl")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import joblib
# import numpy as np
# 
# # --- Load necessary files ---
# try:
#     model = joblib.load("loan_model.pkl")
#     feature_names = joblib.load("feature_names.pkl")
#     # Load all individual LabelEncoders
#     encoders = {
#         'person_gender': joblib.load('person_gender_encoder.pkl'),
#         'person_education': joblib.load('person_education_encoder.pkl'),
#         'person_home_ownership': joblib.load('person_home_ownership_encoder.pkl'),
#         'loan_intent': joblib.load('loan_intent_encoder.pkl'),
#         'previous_loan_defaults_on_file': joblib.load('previous_loan_defaults_on_file_encoder.pkl')
#     }
# except FileNotFoundError:
#     st.error("Model or necessary files not found. Please ensure 'loan_model.pkl', 'feature_names.pkl', and all encoder files are in the directory.")
#     st.stop()
# except Exception as e:
#     st.error(f"Error loading files: {e}")
#     st.stop()
# 
# 
# st.title("Loan Status Prediction App 🏦")
# st.write("Enter borrower details to get a loan approval prediction. (0 = No Default, 1 = Default)")
# 
# # --- Input Fields Grouped by Type ---
# 
# # Define all feature names (in order of training)
# F = {name: i for i, name in enumerate(feature_names)}
# input_array = np.zeros(len(feature_names))
# 
# # --- Categorical Inputs (using Selectbox and Encoders) ---
# st.header("Borrower Demographics")
# 
# # person_gender
# gender_options = encoders['person_gender'].classes_
# person_gender = st.selectbox("Gender", gender_options)
# input_array[F['person_gender']] = encoders['person_gender'].transform([person_gender])[0]
# 
# # person_education
# education_options = encoders['person_education'].classes_
# person_education = st.selectbox("Education Level", education_options)
# input_array[F['person_education']] = encoders['person_education'].transform([person_education])[0]
# 
# # person_home_ownership
# ownership_options = encoders['person_home_ownership'].classes_
# person_home_ownership = st.selectbox("Home Ownership Status", ownership_options)
# input_array[F['person_home_ownership']] = encoders['person_home_ownership'].transform([person_home_ownership])[0]
# 
# # previous_loan_defaults_on_file
# defaults_options = encoders['previous_loan_defaults_on_file'].classes_
# previous_loan_defaults_on_file = st.selectbox("Previous Loan Defaults on File?", defaults_options)
# input_array[F['previous_loan_defaults_on_file']] = encoders['previous_loan_defaults_on_file'].transform([previous_loan_defaults_on_file])[0]
# 
# st.header("Numerical and Loan Details")
# 
# # person_age
# input_array[F['person_age']] = st.number_input("Age", min_value=18.0, max_value=100.0, value=25.0, step=1.0)
# 
# # person_income
# input_array[F['person_income']] = st.number_input("Annual Income ($)", min_value=1000.0, value=60000.0, step=1000.0)
# 
# # person_emp_exp
# input_array[F['person_emp_exp']] = st.number_input("Employment Experience (Years)", min_value=0, max_value=60, value=5)
# 
# # loan_amnt
# input_array[F['loan_amnt']] = st.number_input("Loan Amount Requested ($)", min_value=500.0, value=10000.0, step=100.0)
# 
# # loan_intent
# intent_options = encoders['loan_intent'].classes_
# loan_intent = st.selectbox("Loan Purpose/Intent", intent_options)
# input_array[F['loan_intent']] = encoders['loan_intent'].transform([loan_intent])[0]
# 
# # loan_int_rate
# input_array[F['loan_int_rate']] = st.number_input("Loan Interest Rate (%)", min_value=5.0, max_value=25.0, value=12.0, step=0.1)
# 
# # loan_percent_income
# input_array[F['loan_percent_income']] = st.number_input("Loan/Income Ratio (e.g., 0.1 for 10%)", min_value=0.01, max_value=1.0, value=0.15, step=0.01)
# 
# # cb_person_cred_hist_length
# input_array[F['cb_person_cred_hist_length']] = st.number_input("Credit History Length (Years)", min_value=2.0, max_value=50.0, value=5.0, step=1.0)
# 
# # credit_score
# input_array[F['credit_score']] = st.number_input("Credit Score", min_value=300, max_value=900, value=650)
# 
# 
# if st.button("Predict Loan Status"):
#     # Convert input array to DataFrame in the correct feature order
#     input_df = pd.DataFrame([input_array], columns=feature_names)
# 
#     # Make prediction
#     pred = model.predict(input_df)[0]
# 
#     if pred == 0:
#         st.success(f"Predicted Loan Status: 0 (Likely **No Default**)")
#     else:
#         st.error(f"Predicted Loan Status: 1 (Likely **Default**)")
# 
#     # Optionally show probabilities
#     pred_proba = model.predict_proba(input_df)[0]
#     st.write(f"Confidence for No Default (0): {pred_proba[0]:.2f}")
#     st.write(f"Confidence for Default (1): {pred_proba[1]:.2f}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas
# numpy
# scikit-learn
# joblib

from google.colab import files
files.upload()

